apiVersion: v1
kind: Service
metadata:
  name: ecartordersvc
  labels:
    name: ecartordersvc
spec:
  ports:
    - loadBalancer: 30164
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ecartordersvc
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecartordersvc
spec:
  selector:
    matchLabels:
      app: ecartordersvc
  replicas: 3
  template:
    metadata:
      labels:
        app: ecartordersvc
    spec:
      containers:
      - name: ecartordersvc
        image: ecartordersvc:1.0
        ports:
          - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
          
    
  
